name: Night Stream (30th Jan Only)

on:
  schedule:
    # 00 (min) 17 (hour) 30 (day) 1 (month) * (day of week)
    # 10:30 PM IST = 5:00 PM UTC
    - cron: '00 17 30 1 *'
  workflow_dispatch: # Manually start korar options thakbe

jobs:
  stream:
    runs-on: ubuntu-latest
    # 10:30 PM theke 4:30 AM porjonto 6 ghonta (360 mins)
    timeout-minutes: 360 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Start Streaming
        run: |
          ffmpeg -re -stream_loop -1 -i video.mp4 \
          -c:v libx264 -preset veryfast -b:v 3000k -maxrate 3000k -bufsize 6000k \
          -pix_fmt yuv420p -g 60 -c:a aac -b:a 128k -ar 44100 \
          -f flv "rtmp://a.rtmp.youtube.com/live2/${{ secrets.STREAM_KEY }}"
